# Generated by Django 2.0.5 on 2018-07-02 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecore', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventvenue',
            name='name',
        ),
        migrations.AddField(
            model_name='eventvenue',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecore.Location'),
        ),
    ]
