# Generated by Django 2.0.5 on 2018-05-31 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EvenType',
            new_name='EventType',
        ),
    ]
