# Generated by Django 2.0.5 on 2018-07-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180702_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='status',
            field=models.CharField(default='active', max_length=255),
        ),
    ]
