# Generated by Django 2.0.5 on 2018-06-01 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180531_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtype',
            name='is_layout_based',
        ),
        migrations.AddField(
            model_name='event',
            name='is_layout_based',
            field=models.BooleanField(default=False),
        ),
    ]
