# Generated by Django 2.0.5 on 2018-06-03 23:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20180601_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_layout_based',
        ),
        migrations.AddField(
            model_name='event',
            name='layout',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='event',
            name='layout_type',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='eventvenue',
            name='layout',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='eventvenue',
            name='layout_type',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
