# Generated by Django 2.0.5 on 2018-06-10 03:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20180610_0306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_type', models.CharField(default='none', max_length=255)),
                ('layout', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
