# Generated by Django 2.0.5 on 2018-06-10 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0002_auto_20180610_0231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='file',
            name='object_id',
        ),
    ]
