# Generated by Django 2.0.5 on 2018-06-10 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('file_manager', '0003_auto_20180610_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='content_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='file',
            name='object_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='file',
            name='upload',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
