# Generated by Django 2.0.5 on 2018-07-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_url',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='place_id',
            field=models.CharField(max_length=255),
        ),
    ]
