# Generated by Django 2.0.5 on 2018-06-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='allowed_any',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='access_everything',
            field=models.BooleanField(default=False),
        ),
    ]
