# Generated by Django 2.0.5 on 2018-06-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecore', '0002_auto_20180620_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
