# Generated by Django 2.0.5 on 2018-07-04 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecore', '0003_auto_20180704_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.DecimalField(decimal_places=32, default=0, max_digits=32),
        ),
        migrations.AlterField(
            model_name='location',
            name='lng',
            field=models.DecimalField(decimal_places=32, default=0, max_digits=32),
        ),
    ]
