# Generated by Django 2.0.5 on 2018-07-01 22:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=255)),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('send_to_email', models.CharField(blank=True, max_length=255)),
                ('send_to_mobile', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=255)),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True)),
                ('lid', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
